pizzeria/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'menu', views.MenuItemViewSet)
router.register(r'cart', views.OrderLineViewSet)
router.register(r'cart-text', views.CartViewSet)
router.register(r'toppings', views.ToppingsViewSet)
router.register(r'order', views.OrderViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework')),
]

pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('eshop.urls', namespace='eshop')),
    path('', include('kitchen.urls', namespace='kitchen')),
    path('user/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls),
]

pizzeria/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.user, name='user'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
]

pizzeria/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    # username = forms.CharField(label='Username', max_length=100)
    # first_name = forms.CharField(label='First name', max_length=100)
    # last_name = forms.CharField(label='Last name', max_length=100)
    # email = forms.EmailField(label='Email', max_length=100)
    # password = forms.CharField(label='Password', max_length=100, widget=forms.PasswordInput)
    # password_again = forms.CharField(label='And again..', max_length=100, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'last_name', 'first_name', 'email', 'password']
    password = forms.CharField(label='Password', max_length=100, widget=forms.PasswordInput)

pizzeria/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import UserForm, RegisterForm

from django.contrib.auth.models import User

# Create your views here.

def user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return render(request, "users/user.html", {"message": None})
        else:
            return HttpResponse('failed.')

    if not request.user.is_authenticated:
        return render(request, "users/login.html", {"message": None})
    user_data = User.objects.get(pk=request.user.id)

    context = {
        "user": request.user,
        "form": UserForm(instance=user_data)
    }
    return render(request, "users/user.html", context)

def register(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.username = form.cleaned_data.get('email')
            new_user.save()

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            return HttpResponseRedirect('/')

    else:
        form = RegisterForm()

    return render(request, "users/register.html", {'form': form})

def login_view(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse("eshop:menu"))
    else:
        return render(request, "users/login.html", {"message": "Invalid credentials."})

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {"message": "Logged out."})

def profile(request):
    form = ProfileForm()
    return render(request, "users/user.html", {'form': form})

pizzeria/users/templates/users/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block body %}
<div class="row">
    <div class="col s4 offset-s4 ">
        <h1>Login</h1>
        {% if message %}
            <div>
                {{ message }}
            </div>
        {% endif %}
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <input name="username" type="text" placeholder="username" />
            <input name="password" type="password" placeholder="password"/>
            <input type="submit" class="btn right" value="Login"/>
        </form>
    </div>
</div>
{% endblock %}

pizzeria/users/templates/users/register.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% block head %}
<style>
.helptext {
    display: none;
}
</style>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col s4 offset-s4 ">
        <h1>Sign up</h1>
        {% if message %}
            <div>
                {{ message }}
            </div>
        {% endif %}
        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn right" value="Sign up"/>
        </form>
    </div>
</div>
{% endblock %}

pizzeria/users/templates/users/user.html
{% extends "base.html" %}

{% block title %}
User
{% endblock %}

{% block body %}
<h1>User</h1>
{% if message %}
    <div>
        {{ message }}
    </div>
{% endif %}
Logged in as {{ user }}

<form action="{% url 'users:user' %}" method="post" class="form">
  {% csrf_token %}
  {% comment %} {% form %} {% endcomment %}

  {% buttons %}
    <button type="submit"/>
      Update
    </button>
  {% endbuttons %}
</form>

{% endblock %}