pizzeria/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'menu', views.MenuItemViewSet)
router.register(r'cart', views.OrderLineViewSet)
router.register(r'cart-text', views.CartViewSet)
router.register(r'toppings', views.ToppingsViewSet)
router.register(r'order', views.OrderViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework')),
]

pizzeria/eshop/urls.py
from django.urls import path

from . import views

app_name = 'eshop'
urlpatterns = [
    path('', views.menu, name='menu'),
    path('cart', views.shopping_cart, name='cart'),
]

pizzeria/kitchen/urls.py
from django.urls import path

from . import views

app_name = 'kitchen'
urlpatterns = [
    path('kitchen', views.kitchen_orders, name='kitchen'),
]

pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('eshop.urls', namespace='eshop')),
    path('', include('kitchen.urls', namespace='kitchen')),
    path('user/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls),
]

pizzeria/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.user, name='user'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
]

pizzeria/templates/base.html
<html>
  <head>
  
    <title>
      Pizzeria | {% block title %}{% endblock %}
    </title>

    {% load static %}

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static "css/materialize.css" %}"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <script type="text/javascript" src="{% static "js/eshop.js" %}"></script>
    {% block head %}{% endblock %}

  </head>
  <body>
  
  <nav>
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo"><i class="material-icons">fastfood</i>Pizzeria</a>
        <ul class="right hide-on-med-and-down">

          {% if user.is_authenticated %}
            <li>{{ user }}</li>
          {% endif %}
          
          <li><a href="{% url 'eshop:menu' %}" title="Food menu"><i class="material-icons">restaurant_menu</i></a></li>

          {% if user.is_authenticated %}
            <li><a href="{% url 'eshop:cart' %}" title="Shopping cart"><i class="material-icons">local_grocery_store</i></a></li>
            <li><a href="{% url 'users:logout' %}" title="Log outt">Log out</a></li>
          {% else %}
            <li><a href="{% url 'users:user' %}" title="Log in">Log in</a></li>
            <li><a href="{% url 'users:register' %}" title="Sign up!">Register</a></li>
          {% endif %}

          {% if user.is_staff %}
            <li><a href="{% url 'kitchen:kitchen' %}" title="See orders"><i class="material-icons">replay</i></a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
  
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>

    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>

    <script>
       M.AutoInit();
    </script>

    {% block footer %}
    {% endblock %}

  </body>
</html>